#!/usr/bin/env bash
#
# taskboard.sh - Generate TASKBOARD.md from task files
#
# Usage: .claude/scripts/taskboard.sh
#
set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TASKS_DIR="$REPO_ROOT/.claude/tasks"
OUTPUT_FILE="$REPO_ROOT/TASKBOARD.md"

# Colors for terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[OK]${NC} $1"
}

# Count tasks in each state
count_todo=$(find "$TASKS_DIR/todo" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
count_doing=$(find "$TASKS_DIR/doing" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
count_done=$(find "$TASKS_DIR/done" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')

log_info "Generating TASKBOARD.md..."
log_info "Found: $count_todo todo, $count_doing doing, $count_done done"

# Start generating the taskboard
cat > "$OUTPUT_FILE" << 'HEADER'
# Taskboard

> Auto-generated by `.claude/scripts/taskboard.sh`
> Last updated: TIMESTAMP

## Summary

| Status | Count |
|--------|-------|
HEADER

# Replace timestamp
sed -i '' "s/TIMESTAMP/$(date '+%Y-%m-%d %H:%M:%S')/" "$OUTPUT_FILE" 2>/dev/null || \
sed -i "s/TIMESTAMP/$(date '+%Y-%m-%d %H:%M:%S')/" "$OUTPUT_FILE"

# Add counts
echo "| Doing | $count_doing |" >> "$OUTPUT_FILE"
echo "| Todo | $count_todo |" >> "$OUTPUT_FILE"
echo "| Done | $count_done |" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Function to extract task title from file
get_task_title() {
    local file="$1"
    head -5 "$file" | grep -m1 "^# Task:" | sed 's/^# Task: //' || basename "$file" .md
}

# Function to extract priority from filename
get_priority_label() {
    local filename="$1"
    case "${filename:0:3}" in
        001) echo "Critical" ;;
        002) echo "High" ;;
        003) echo "Medium" ;;
        004) echo "Low" ;;
        *) echo "Unknown" ;;
    esac
}

# In Progress section
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## In Progress" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ "$count_doing" -eq 0 ]; then
    echo "_No tasks in progress_" >> "$OUTPUT_FILE"
else
    for file in "$TASKS_DIR/doing"/*.md; do
        [ -f "$file" ] || continue
        filename=$(basename "$file")
        title=$(get_task_title "$file")
        priority=$(get_priority_label "$filename")
        echo "- **[$filename](.claude/tasks/doing/$filename)** - $title [$priority]" >> "$OUTPUT_FILE"
    done
fi
echo "" >> "$OUTPUT_FILE"

# Todo section
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Todo" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ "$count_todo" -eq 0 ]; then
    echo "_No pending tasks_" >> "$OUTPUT_FILE"
else
    # Sort by filename (which gives priority order)
    for file in $(find "$TASKS_DIR/todo" -maxdepth 1 -name "*.md" 2>/dev/null | sort); do
        [ -f "$file" ] || continue
        filename=$(basename "$file")
        title=$(get_task_title "$file")
        priority=$(get_priority_label "$filename")
        echo "- **[$filename](.claude/tasks/todo/$filename)** - $title [$priority]" >> "$OUTPUT_FILE"
    done
fi
echo "" >> "$OUTPUT_FILE"

# Done section (last 10)
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Recently Completed (Last 10)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ "$count_done" -eq 0 ]; then
    echo "_No completed tasks_" >> "$OUTPUT_FILE"
else
    # Sort by modification time, most recent first, limit to 10
    for file in $(find "$TASKS_DIR/done" -maxdepth 1 -name "*.md" -exec ls -t {} + 2>/dev/null | head -10); do
        [ -f "$file" ] || continue
        filename=$(basename "$file")
        title=$(get_task_title "$file")
        echo "- **[$filename](.claude/tasks/done/$filename)** - $title" >> "$OUTPUT_FILE"
    done
fi
echo "" >> "$OUTPUT_FILE"

# Footer
cat >> "$OUTPUT_FILE" << 'FOOTER'
---

## Quick Commands

```bash
# Regenerate this file
.claude/scripts/taskboard.sh

# Run agent for 1 task
./bin/agent 1

# Run agent for 5 tasks (default)
./bin/agent

# Check task counts
echo "TODO: $(ls .claude/tasks/todo/*.md 2>/dev/null | wc -l)"
echo "DOING: $(ls .claude/tasks/doing/*.md 2>/dev/null | wc -l)"
echo "DONE: $(ls .claude/tasks/done/*.md 2>/dev/null | wc -l)"
```
FOOTER

log_success "Generated $OUTPUT_FILE"
